//1.需要创建两个分支基于main的分支，并使用合并方法，改在同一行问题
//old_______我这是冲突old测试第二种情况（先推送后变基）sdhflaf
//sahdfhsl
//现在我新的文件改在同一行了，需要处理冲突
//还需要添加一个文件看看
//2.远程有文件，但是本地删除了文件
//hjfdfsdfkl
//dafnkllsfj
//sdfklas
//sdaflkn
//sasdfsa